# action.yml
name: 'Directory Listing for Github Page'
description: 'Github Action to generate directory listing index for Github Pages'

author: 'rajibdpi'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  FOLDER:
    description: 'folder to start index generations'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FOLDER }}
